modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/raulsmartin/Food-Expansion/issues"
showAsResourcePack=false

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/food-expansion-reimagined"
    logoFile="logo.png"
    credits="Thanks to Lellson for his original Food Expansion."
    authors="${mod_authors}"
    description='''${mod_description}'''

    [[dependencies.${mod_id}]]
        modId="forge"
        mandatory=true
        versionRange="${forge_version_range}"
        ordering="NONE"
        side="BOTH"

    [[dependencies.${mod_id}]]
        modId="minecraft"
        mandatory=true
        versionRange="${minecraft_version_range}"
        ordering="NONE"
        side="BOTH"